### ISSUE TITLE
Codegen for mocks fails on filename case mismatch.

### ISSUE THREAD

**Issue by vaneek** [smithy-lang/smithy-python#239]
Using the PDK [shopping list demo](https://aws.github.io/aws-pdk/getting_started/shopping_list_app.html) , the generated code breaks during the build process with the following error;

```
File "/home/ec2-user/environment/tpdk/packages/api/generated/infrastructure/python/orgapi_python_infra/mock_integrations.py", line 23, in delete_shopping_list_200
infra:     with open(path.join(MOCK_DATA_PATH, "DELETE{}-200.json".format("/shopping-list/{shoppingListId}".replace("/", "-")).lower()), "r") as f:
infra:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
infra: FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/environment/tpdk/packages/api/generated/infrastructure/python/orgapi_python_infra/../mocks/delete-shopping-list-{shoppinglistid}-200.json'
```

The code performs a `.lower()` on the whole path rather than just the verb. The name of  the generated json file  is  `delete-shopping-list-{shoppingListId}-200.json`. This may also catch  upstream directories with caps in their name.

The  smithy definition is;
```
@http(method: "DELETE", uri: "/shopping-list/{shoppingListId}")
@handler(language: "python")
operation DeleteShoppingList {
    input := {
        @required
        @httpLabel
        shoppingListId: ShoppingListId
    }
    output := with [ShoppingListIdMixin] {}
    errors: [NotFoundError]
}
```

**Comment by JordonPhillips** [comment]
The PDK isn't making use of this project, I would recommend opening this issue in [aws/aws-pdk](https://github.com/aws/aws-pdk)

**Comment by vaneek** [comment]
Makes no sense. This is code generated by Smithy. Is there another Smithy project?
